services:
  mysql:
    image: mysql:8.3
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api_network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD --silent" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  migrate:
    image: migrate/migrate:v4.17.1
    restart: "no"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - api_network
    volumes:
      - ./database/migrations:/migrations
    entrypoint:
      [
        "sh",
        "-c",
        "migrate -path /migrations -database \"$DATABASE_URL?x-migrations-table=schema_migrations\" up"
      ]

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - api_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    container_name: php_api
    ports:
      - "8080:8080"
    volumes:
      - .:/api
    working_dir: /api
    networks:
      - api_network

  sqs:
    image: softwaremill/elasticmq:latest
    container_name: elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    networks:
      - api_network

  seed-sqs:
    image: amazon/aws-cli
    depends_on:
      - sqs
    entrypoint:
      - aws
      - --endpoint-url=${SQS_URL}
      - sqs
      - create-queue
      - --queue-name
      - ${QUEUE_NAME}
      - --region
      - ${AWS_DEFAULT_REGION}
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    networks:
      - api_network

  runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    restart: "no"
    env_file:
      - .env
    container_name: php_runner
    depends_on:
      api:
        condition: service_started
      seed-sqs:
        condition: service_completed_successfully
    networks:
      - api_network

volumes:
  mysql_data:

networks:
  api_network: