FROM php:8.5-fpm

# Install common extensions
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    libzip-dev \
    libxml2-dev \
    && docker-php-ext-install \
        zip \
        pdo_mysql \
        soap \
    && rm -rf /var/lib/apt/lists/*

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Project root
WORKDIR /app

# Copy Composer files first
COPY composer.json composer.lock* ./

# Install dependencies
RUN composer install \
    --no-interaction \
    --prefer-dist \
    --no-dev \
    --optimize-autoloader

# Copy application code
COPY src/ ./src/
COPY config/ ./config/
COPY importers/ ./importers/

# Useful while debugging
RUN ls -la
RUN ls -la /app/importers/runner
RUN ls -la /app/vendor

CMD ["php", "importers/runner/main.php"]