FROM php:8.5-cli

# Install common extensions
RUN apt-get update && apt-get install -y \
        git \
        unzip \
        zip \
        libzip-dev \
        libxml2-dev \
    && docker-php-ext-install zip pdo_mysql soap \
    && rm -rf /var/lib/apt/lists/*

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /api

# Install Composer
COPY composer.json composer.lock* ./

RUN if [ -f composer.json ]; then composer install; fi

COPY . .

EXPOSE 8080

CMD ["php", "-S", "0.0.0.0:8080", "-t", "public"]